
services:
  kavita:
    image: jvmilazz0/kavita:0.9.0@sha256:36aab0c578d488f8b10bd33910953b50965aff9ac6adc476ef4692c38c60427e
    container_name: kavita
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TZ=Your/Timezone
    volumes:
      - /your/path/to/manga:/manga
      - /your/path/to/comics:/comics
      - /your/path/to/books:/books
      - /your/path/to/saved/config:/kavita/config     # /kavita/config must not be changed