
services:
  kavita:
    image: jvmilazz0/kavita:0.9.1@sha256:31181a32f0dda73cae68721867028a7253d57881b58bea5754cd9e578e75421a
    container_name: kavita
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TZ=Your/Timezone
    volumes:
      - /your/path/to/manga:/manga
      - /your/path/to/comics:/comics
      - /your/path/to/books:/books
      - /your/path/to/saved/config:/kavita/config     # /kavita/config must not be changed