
services:
  kavita:
    image: jvmilazz0/kavita:0.9.1@sha256:454f2a77ac740b70c58cc7300a11122fc9ce7b7e2161ef5b0d1df8f81067cc85
    container_name: kavita
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - TZ=Your/Timezone
    volumes:
      - /your/path/to/manga:/manga
      - /your/path/to/comics:/comics
      - /your/path/to/books:/books
      - /your/path/to/saved/config:/kavita/config     # /kavita/config must not be changed