
services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:5.4.1@sha256:79e24745650eda07631c32a6975e3d5e8ee165ebac6f28d2fb9dd9c13f01d351
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'America/Toronto'
    # Volumes store your data between container upgrades
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped