
services:
  n8n:
    image: n8nio/n8n:2.39.0@sha256:c7d3301deee1c5a7571a124d14ba9b3f973fd55d515ee87b81cd62f7b4e75b40
    restart: unless-stopped
    ports:
      - "${N8N_PORT}:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - WEBHOOK_TUNNEL_URL=${N8N_TUNNEL_URL}
      - N8N_PORT=${N8N_PORT}
    # Add other environment variables as needed, e.g., for database connection
    # - DB_TYPE=
    # - DB_POSTGRESDB_HOST=
    # - DB_POSTGRESDB_DATABASE=
    # - DB_POSTGRESDB_USER=
    # - DB_POSTGRESDB_PASSWORD=
    volumes:
      - ./data:/home/node/.n8n