
services:
  server:
    image: gitea/gitea:28.0.0@sha256:a9dc25679ebdd33356242d2e0667cc220043745e8339922879f187c20329a42e
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=http://localhost:3000
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"   # Web interface
      - "222:22"      # SSH access
    networks:
      - gitea-net

volumes:
  gitea_data:

networks:
  gitea-net:
    driver: bridge