
services:
  server:
    image: gitea/gitea:1.27.3@sha256:87a67ee09d3ae0d1df5fda5dcda3e2a1f9236a45b0a59025d6e00e46adc43bef
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=http://localhost:3000
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"   # Web interface
      - "222:22"      # SSH access
    networks:
      - gitea-net

volumes:
  gitea_data:

networks:
  gitea-net:
    driver: bridge