
services:
  server:
    image: gitea/gitea:1.27.2@sha256:d20286ca2b2e170fdf628e7231b8a31a3220ade39ff462b55041d43d1fc757dd
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=http://localhost:3000
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"   # Web interface
      - "222:22"      # SSH access
    networks:
      - gitea-net

volumes:
  gitea_data:

networks:
  gitea-net:
    driver: bridge