
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.1.0@sha256:d0aeae2e24387af7267d38c8573692b61e0543aa083c689ad04f32267fe6706a
    container_name: homepage
    volumes:
      - ./config:/app/config  # You can adapt the path to whatever suits you.
      - /var/run/docker.sock:/var/run/docker.sock  # optional: enables Docker integration
    ports:
      - 3000:3000
    restart: unless-stopped