
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.2.0@sha256:753eeb0cc22ab7baad39ed47cbd1aae14e193dd1b264e965f193a9ea1d1e1bdd
    container_name: homepage
    volumes:
      - ./config:/app/config  # You can adapt the path to whatever suits you.
      - /var/run/docker.sock:/var/run/docker.sock  # optional: enables Docker integration
    ports:
      - 3000:3000
    restart: unless-stopped