
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v2.3.0@sha256:f820276654539cdc2cf0169f28188d135919a7984fad76d83d8d5ff1383f3705
    container_name: homepage
    volumes:
      - ./config:/app/config  # You can adapt the path to whatever suits you.
      - /var/run/docker.sock:/var/run/docker.sock  # optional: enables Docker integration
    ports:
      - 3000:3000
    restart: unless-stopped