
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.18@sha256:c4c627f687668c5a02ab410d8473712c77be7f1f0ea4f8d624d2a1392c495e76
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8084:80"
    volumes:
      - /opt/selfhost/data:/srv  # Replace with the folder you want to browse
      - filebrowser_config:/config

volumes:
  filebrowser_config: