
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.41.0@sha256:b7e05896700acf278bc4ee90cac1e13f17d7a983dfbe5744ee3690ee11dce766
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8084:80"
    volumes:
      - /opt/selfhost/data:/srv  # Replace with the folder you want to browse
      - filebrowser_config:/config

volumes:
  filebrowser_config: