
services:
  filebrowser:
    image: filebrowser/filebrowser:v2.63.17@sha256:271ec822a03112ee8d2fc7042e8434995dfa74421e6a48e031be68c88fcded1c
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8084:80"
    volumes:
      - /opt/selfhost/data:/srv  # Replace with the folder you want to browse
      - filebrowser_config:/config

volumes:
  filebrowser_config: