
services:
  portainer:
    image: portainer/portainer-ce:2.32.0@sha256:14c4697739979d67d097b9ff351f3bde1ee2b9511197cd55cb43dc1d41ad72c2
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"  # HTTPS UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: