services:
  minio:
    image: minio/minio:RELEASE.2025-05-24T17-08-30Z@sha256:a616cd8f37758b0296db62cc9e6af05a074e844cc7b5c0a0e62176d73828d440
    container_name: minio
    restart: unless-stopped
    ports:
      - "${MINIO_API_PORT}:9000"                                      # MinIO S3 API port
      - "${MINIO_CONSOLE_PORT}:9001"                                  # MinIO Console port
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}                # Optional: default bucket to create
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: