
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.3@sha256:4538137bc5af902dece165f2bf73776d9cf4eafb6dd714670724af8f3eb77764
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - "${JELLYSEERR_PORT}:5055"
    environment:
      - TZ=${TZ}
    volumes:
      - jellyseerr_config:/app/config

volumes:
  jellyseerr_config: