
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.2@sha256:98296861cf3caebe8ada72e5dbe2729fb10cdb2042d2b82e86065bf870418587
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - "${JELLYSEERR_PORT}:5055"
    environment:
      - TZ=${TZ}
    volumes:
      - jellyseerr_config:/app/config

volumes:
  jellyseerr_config: