
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.1@sha256:c9d751b5a0c1cb8e2e32aee9a983c811a439f0ab13582c6bdd13d93f86a61954
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - "${JELLYSEERR_PORT}:5055"
    environment:
      - TZ=${TZ}
    volumes:
      - jellyseerr_config:/app/config

volumes:
  jellyseerr_config: