
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.6.0@sha256:8f320036d937d84c385ea5800f87d69ba16ec4d3770fccf6cad803b5e8d66a52
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - "${JELLYSEERR_PORT}:5055"
    environment:
      - TZ=${TZ}
    volumes:
      - jellyseerr_config:/app/config

volumes:
  jellyseerr_config: