
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:1.9.2@sha256:8f708df0ce3f202056bde5d7bff625eb59efe38f4ee47bdddc7560b6e4a5a214
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - "${JELLYSEERR_PORT}:5055"
    environment:
      - TZ=${TZ}
    volumes:
      - jellyseerr_config:/app/config

volumes:
  jellyseerr_config: